module.exports = `
<!-- Beginning of the rendered Markdown -->

<h1 align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="assets/banner_dark_theme/<#banner_dark>">
    <source media="(prefers-color-scheme: light)" srcset="assets/banner_light_theme/<#banner_light>">
    <img alt="TEXT" src="assets/banner_light_theme/light-banner-1.png">
  </picture>
</h1>

<p align="left"> <img alt="orel138" src="https://komarev.com/ghpvc/?username=orel138&label=Profile%20views&color=ffbe6f&style=flat-square" /> </p>

<h3 align="left">Languages and Tools</h3>
<p>
<img alt="STM32" src="https://img.shields.io/badge/STM32%20-%20?style=flat-square&logo=stmicroelectronics&logoColor=white&color=03234b" />
<img alt="Amazon AWS" src="https://img.shields.io/badge/Amazon%20AWS%20-%20?style=flat-square&logo=amazonaws&logoColor=white&color=232f3e" />
<img alt="Arduino" src="https://img.shields.io/badge/Arduino%20-%20?style=flat-square&logo=arduino&logoColor=white&color=00878f" />
<img alt="github actions" src="https://img.shields.io/badge/Github%20Actions%20-%20?style=flat-square&logo=github-actions&logoColor=white&color=2088ff" />
<img alt="Docker" src="https://img.shields.io/badge/Docker%20-%20?style=flat-square&logo=docker&logoColor=white&color=2496ed" />
<img alt="git" src="https://img.shields.io/badge/Git%20-%20?style=flat-square&logo=git&logoColor=white&color=f05032" />
</p>

> "Your body is a reflection of what you eat" - Me: <#RandomDish>

> 🥠 Fortune cookie : <#fortune_cookie>

<#day_before_new_years> days before new year

<div align="left">
  Today's weather for <img src="https://cdn-icons-png.flaticon.com/512/197/197560.png" width="13"/> <b>Grenoble, France</b>: <b><#todays_temperature>°C (felt <#todays_felt_temperature>°C), <#todays_weather></b>.
  </div>
<div align="left">
  The ☀️ rise 🌄 at <#todays_sun_rise> and sets 🌇 at <#todays_sun_sets>
  </div>
<br>

<div align="center">
  <sub>
  This file is automatically generated every day
  </div>
<div align="center">
  <sub>
  Last update on <#today_date>
  </div>
<br>

<!-- End of the rendered Markdown -->
<!-- The following content will not appear in the rendered Markdown -->
`;